INCLUDES = /home/futag/Futag-tests/pugixml/pugixml-1.12/.futag-install/include
FLAGS = -g -fsanitize=address
all:
	$(CXX) $(FLAGS) -I$(INCLUDES) xpath_query.cpp  /home/futag/Futag-tests/pugixml/pugixml-1.12/.futag-install/lib/libpugixml.a -lm